import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import getConfig from 'next/config'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TopBarChart from '../components/topbar'
import { HostInfo, LastDaysInfo } from '../models/host'
import DateAeraChart from '../components/dateaera'
import { useEffect, useState } from 'react'

const { serverRuntimeConfig } = getConfig()

const Home = (props: { last7dayscount: LastDaysInfo[], top10domainscount : HostInfo[] }) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Flow statistics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBarChart data={props.top10domainscount} />
      <DateAeraChart data={props.last7dayscount} />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  // Fetch data from external API
  if (!serverRuntimeConfig.backend_host) {
    return {
      notFound: true,
    }
  }
  const host = serverRuntimeConfig.backend_host
  const last7dayscount = await (await fetch(host + "/last7daystatistics")).json()
  const top10domainscount = await (await fetch(host + "/top10domains")).json()

  if (!last7dayscount || !top10domainscount) {
    return {
      notFound: true,
    }
  }
  // Pass host to the page via props
  return { props: { last7dayscount, top10domainscount } }
}

export default Home
